### ISSUE TITLE
help form type

### ISSUE THREAD

**Issue by fadoe** [symfony2admingenerator/AvocodeFormExtensionsBundle#102]
I don't know if it is a admin generator or a form extension problem. When I use 

```
title:
   label: blablub
   formOptions:
        help: Somehelp
```

this field changed to required. I have a form type checkbox. Without the help I can check and uncheck the field. With help I must check or I can't safe. Same problem with a input field in the filter. Without help I can leave the text field empty, filter works. With help I must insert something.
