### ISSUE TITLE
JavaScript error in collection upload if using quotes in nameable or editable field.

### ISSUE THREAD

**Issue by satiricon** [symfony2admingenerator/AvocodeFormExtensionsBundle#124]
The config:

``` yaml
      items:
        label:            ' Images'
        dbType:           collection
        formType:         afe_collection_upload
        addFormOptions:
          sortable: true
          editable:         [ name, filename, description, author, position ]
          type:             "album_asset"
          previewMaxWidth:    120
          acceptFileTypes:    /(\.|\/)(gif|jp?g|png)$/i
          allow_add:        true
          allow_delete:     true
          error_bubbling:   false
          options:
            data_class:     Bn\WebBundle\Entity\Asset
```

If for any reason I add something like `this is "the description"` as the description in the form of any uploaded file it will cause a JavaScript error as the line 129 in form_javascripts.html.twig

``` twig
{{ field|e4js }}: {{ attribute(item, field)|default('')|e4js }},
```

Doesn't correctly escapes quotes.

if I change the line to:

``` twig
{{ field|e4js }}: "{{ attribute(item, field)|default('')|e('js') }}",
```

It works flawlessly.

Is there a reason for not using the default twig escaper?
