### ISSUE TITLE
Placeholder translation in afe_select2_entity

### ISSUE THREAD

**Issue by montabou** [symfony2admingenerator/AvocodeFormExtensionsBundle#135]
In my params: fields: I have:

```
my_entity:
    formType: afe_select2_entity
    addFormOptions:
        configs:
            placeholder: my_entity.placeholder
```

The generated code in EditType is:

```
 'configs' =>   array(    'placeholder' => '$this->translator->trans("my_entity.placeholder")'
```

which seems correct

but the generated code in js is:

```
$field.select2({"placeholder": "my_entity.placeholder"})
```

I've tried to add translation into:
- Admingenerator
- Admin
- AvocodeFormExtensions
- messages

but no one works.
