### ISSUE TITLE
Collection Upload : Option deletable not working

### ISSUE THREAD

**Issue by rpostolov** [symfony2admingenerator/AvocodeFormExtensionsBundle#140]
Hi,

i have some issue with collection upload. I'm using Avocde, vich uploader both with admingenerator.

It's show me the form, and the upload works fine (after remove some option like nameable and editable because of some issues, see : #139 ) , but after uploading and saving i try to check the input for deleting the file and it doesn't work.

In fact the checkbox have class 'disabled' and i don't know why because i set the option deletable at true, see here all the configuration :

``` yaml
images:
        label:            Images
        dbType:           collection
        formType:         afe_collection_upload
        addFormOptions:
            primary_key:          id
            nameable:             false
            sortable:             true
            sortable_field:       position
            editable:             [ legende ]
            type:                 \Tranoi\DesignerInscritBundle\Form\Type\ImageAdmin\EditType
            maxNumberOfFiles:     5
            maxFileSize:          500000
            minFileSize:          1000
            acceptFileTypes:      /(\.|\/)(gif|jpe?g|png)$/i
            loadImageFileTypes:   /^image\/(gif|jpe?g|png)$/i
            loadImageMaxFileSize: 250000
            previewMaxWidth:      100
            previewMaxHeight:     100
            previewAsCanvas:      true
            previewFilter:        thumb_gallery_images
            prependFiles:         false
            allow_add:            true
            allow_delete:         true
            error_bubbling:       true
            options:
                data_class:       Tranoi\DesignerInscritBundle\Entity\Image
```

When i took a look to the documentation i dont have the explanation for this some options, mays not updated ?

If you have some idea ?

Thanks guys !
