### ISSUE TITLE
Upload collection error

### ISSUE THREAD

**Issue by denys281** [symfony2admingenerator/AvocodeFormExtensionsBundle#15]
When I submit  my form I have error:

`Warning: Invalid argument supplied for foreach() in .../vendor/avocode/form-extensions-bundle/Avocode/FormExtensionsBundle/Form/EventListener/CollectionUploadSubscriber.php line 122`

And when I upload images, there are no preview for images.

My config:

``` yml
gallery:
        label:            Зображення
        dbType:           collection
        formType:         collection_upload
        addFormOptions:
          nameable:         true
          nameable_field:   name
          editable:         [name]
          type:             \Webmil\Frontend\AboutBundle\Form\AboutGalleryType
          acceptFileTypes:            /(\.|\/)(gif|jpe?g|png)$/i
          previewSourceFileTypes:     /^image\/(gif|jpeg|png)$/
          previewAsCanvas:            true
          prependFiles:               false 
          allow_add:                  true
          allow_delete:               true
          error_bubbling:   false
          options:
            data_class:    \Webmil\Frontend\AboutBundle\Entity\AboutGallery       
```

My form type:

``` php
  public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('id', null)
            ->add('name', null)
        ;
    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Webmil\Frontend\AboutBundle\Entity\AboutGallery'
        ));
    }

    public function getName()
    {
        return 'webmil_frontend_aboutbundle_aboutgallerytype';
    }
```
