### ISSUE TITLE
Field to be sorted

### ISSUE THREAD

**Issue by rpostolov** [symfony2admingenerator/AvocodeFormExtensionsBundle#153]
Hi,

I have a simple question, i search for the solution but i couldn't find an answer.

I have a field which is a list of countries, but its not sorted. I want to know if it's possible to add an sort option in the generator.yml and if it's yes how.

Here is a part of my admin-generator.yml file

```
fields:      
      country:
        label: Country
        addFormOptions:
         required: true
```

Thanks :)
