### ISSUE TITLE
Error when using single_upload

### ISSUE THREAD

**Issue by thibmonier** [symfony2admingenerator/AvocodeFormExtensionsBundle#46]
I'm trying to use a single_upload, I follow instructions in documentation with VichUploader but I have this error when I'm doing a cache:clear or when I'm trying to display the list.

``` SHELL
An exception has been thrown during the rendering of a template ("The dbType "virtual" is only for list implemented (column "articleImage" in "Acme\NewsBundle\Entity\Article")") in "Edit/FormBuilderTemplate.php.twig".
```

My config in generator.yml

``` YAML
    fields: 
        articleImage:
            label:            Image
            formType:         single_upload
            addFormOptions:
                nameable:       articleImageName
                deleteable:     articleImagePath
                data_class:     Symfony\Component\HttpFoundation\File\File
```

And my entity

``` PHP
/**
     * @Assert\File(
     *     maxSize="2M",
     *     mimeTypes={"image/png", "image/jpeg", "image/pjpeg"}
     * )
     * @Vich\UploadableField(mapping="article_image", fileNameProperty="articleImageName")
     * @var File $articleImage
     */
    protected $articleImage;

    /**
     * (Optional) holds file name
     *
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $articleImageName;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $articleImagePath;

```

Any ideas ?
