### ISSUE TITLE
[CollectionUpload] Could not load type 

### ISSUE THREAD

**Issue by denys281** [symfony2admingenerator/AvocodeFormExtensionsBundle#84]
Hi! I don't now if this bug of AvocodeForm. I have collection upload and all works. Today I start my project in new machine, so I update vendors. And collection upload gives me error

```
Could not load type "\Webmil\Frontend\ProductBundle\Form\ProductGalleryType"
```

I use last version of avocode with sf 2.3.7. I saw in update log of sf 2.3.7 but I can't find anything there, what can break my code. 

``` yml
gallery:
        label:            Зображення
        dbType:           collection
        formType:         afe_collection_upload
        addFormOptions:
          maxNumberOfFiles: 20
          nameable:         true 
          nameable_field:   name
          editable:         [name]
          type:             \Webmil\Frontend\ProductBundle\Form\ProductGalleryType
          acceptFileTypes:            /(\.|\/)(gif|jpe?g|png)$/i
          loadImageFileTypes:     /^image\/(gif|jpeg|png)$/
          previewMaxWidth:            100
          previewMaxHeight:           100
          previewAsCanvas:            true
          prependFiles:               false 
          allow_add:                  true
          allow_delete:               true
          options:
            data_class:    \Webmil\Frontend\ProductBundle\Entity\ProductGallery    
```

And my form:

``` php
<?php

namespace Webmil\Frontend\ProductBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class ProductGalleryType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('id', null)
            ->add('name', null);
//            ->add('imageName', null);
//            ->add('createdAt')
//            ->add('updatedAt')
//            ->add('product');
    }

    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Webmil\Frontend\ProductBundle\Entity\ProductGallery'
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'webmil_frontend_productbundle_productgallerytype';
    }
}


```
