### ISSUE TITLE
afe_datetime_picker does not work properly

### ISSUE THREAD

**Issue by martinratinaud** [symfony2admingenerator/AvocodeFormExtensionsBundle#99]
This bug is has been reproduced in my environment and on AvocodeFormExtensionSample by @sescandell which i spretty straightforward

``` yaml

fields:
        publishDate:
            formType: afe_datetime_picker
```

this shows a double select box where time picker does work (is not clickable)
and where fields are on two lines instead of one

![screen shot 2013-12-11 at 17 24 35](https://f.cloud.github.com/assets/4191809/1725499/c6ff2114-6280-11e3-94f1-1e2a82387aa8.png)

Maybe an idea would be to use http://tarruda.github.io/bootstrap-datetimepicker/ instead of splitting the field datetime field in two date and time fields
